export enum ReturnStatus {
    REQUESTED = "REQUESTED",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
    PICKUP_SCHEDULED = "PICKUP_SCHEDULED",
    PICKED_UP = "PICKED_UP",
    RECEIVED = "RECEIVED",
    REFUND_PENDING = "REFUND_PENDING",
    REFUNDED = "REFUNDED",
    CANCELLED = "CANCELLED",
}

export enum ReturnReason {
    DAMAGED = "DAMAGED",
    DEFECTIVE = "DEFECTIVE",
    WRONG_ITEM = "WRONG_ITEM",
    SIZE_ISSUE = "SIZE_ISSUE",
    QUALITY_ISSUE = "QUALITY_ISSUE",
    NOT_AS_EXPECTED = "NOT_AS_EXPECTED",
    OTHER = "OTHER",
}

export enum RefundMethod {
    ORIGINAL_PAYMENT = "ORIGINAL_PAYMENT",
    WALLET = "WALLET",
    UPI = "UPI",
}