export enum ShipmentStatus {
    PENDING = "PENDING",
    PACKED = "PACKED",
    SHIPPED = "SHIPPED",
    IN_TRANSIT = "IN_TRANSIT",
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
    DELIVERED = "DELIVERED",
    FAILED_DELIVERY = "FAILED_DELIVERY",
    RETURNED_TO_ORIGIN = "RETURNED_TO_ORIGIN",
    CANCELLED = "CANCELLED",
}

export enum ShippingCarrier {
    DELHIVERY = "DELHIVERY",
    BLUEDART = "BLUEDART",
    DTDC = "DTDC",
    ECOM_EXPRESS = "ECOM_EXPRESS",
    INDIA_POST = "INDIA_POST",
    SELF_DELIVERY = "SELF_DELIVERY",
    OTHER = "OTHER",
}