const ENDPOINTS = {
    AUTH: {
        LOGIN: "auth/login",
        LOGOUT: "auth/logout",
        FORGOT_PASSWORD: "auth/forgot-password",
        RESET_PASSWORD: "auth/reset-password",
        VERIFY_FORGET_PASSWORD: "auth/verify-forgot-password-otp"
    },
    USER: {
        PROFILE: "/user/profile",
        UPDATE_PROFILE: "/user/profile",
        AVATAR: "/user/avatar",
        CHANGE_PASSWORD: "/user/change-password"
    },
    ADMIN: {
        FETCH: "/admins/all",
        SEARCH_USERS: "/admins/search-users",
        PROMOTE: (id: string) => `/admins/${id}/promote`,
        DEMOTE: (id: string) => `/admins/${id}/demote`,
    },
    CUSTOMER: {
        FETCH: "/admins/customers",
        TOGGLE_BLOCK: (id: string) => `/admins/customers/${id}/block`,
    },
    VENDOR: {
        FETCH: "/vendor",
        BY_ID: (id: string) => `/vendor/${id}`,
        APPROVE: (id: string) => `/vendor/${id}/approve`,
        REJECT: (id: string) => `/vendor/${id}/reject`,
        BLOCK: (id: string) => `/vendor/${id}/block`,
        STATUS: (id: string) => `/vendor/${id}/status`,
        DELETE: (id: string) => `/vendor/${id}`,
    },
    ORDER: {
        FETCH: "/order/admin/all",
        UPDATE_STATUS: (id: string) => `/order/${id}/status`,
        CANCEL: (id: string) => `/order/${id}/cancel`,
    },
    SHIPMENT: {
        FETCH: "/shipments/admin/all",
        UPDATE_STATUS: (id: string) => `/shipments/${id}/status`,
        ASSIGN_COURIER: (id: string) => `/shipments/${id}/assign-courier`,
        CANCEL: (id: string) => `/shipments/${id}/cancel`,
        BY_ORDER: (orderId: string) => `/shipments/order/${orderId}`,
    },
    CATEGORY: {
        FETCH: "/category/all",
        FETCH_BY_ID: (id: string) => `/category/id/${id}`,
        CREATE: "/category/add",
        UPDATE: (id: string) => `/category/update/${id}`,
        DELETE: (id: string) => `/category/delete/${id}`,
        RESTORE: (id: string) => `/category/${id}/restore`,
        PERMANENT_DELETE: (id: string) => `/category/${id}/permanent-delete`,
    },
    BRAND: {
        FETCH: "/brand/get",
        CREATE: "/brand/add",
        UPDATE: (id: string) => `/brand/update/${id}`,
        DELETE: (id: string) => `/brand/delete/${id}`,
        RESTORE: (id: string) => `/brand/${id}/restore`,
        PERMANENT_DELETE: (id: string) => `/brand/${id}/permanent-delete`,
    },
    PRODUCTS: {
        FETCH: "/product/all",
        FETCH_SINGLE: (slug: string) => `/product/${slug}`,
        CREATE: "/product/add",
        UPDATE: (slug: string) => `/product/${slug}/update`,
        UPDATE_MEDIA: (slug: string) => `/product/${slug}/update/media`,
        DELETE_IMAGE: (slug: string) => `/product/${slug}/image`,
        DELETE: (slug: string) => `/product/${slug}/delete`,
        APPROVE: (slug: string) => `/product/${slug}/approve`,
        TOGGLE_FEATURED: (slug: string) => `/product/${slug}/featured`,
        RESTORE: (slug: string) => `/product/${slug}/restore`,
        PERMANENT_DELETE: (slug: string) => `/product/${slug}/permanent-delete`,
    },
    DASHBOARD: {
        OVERVIEW: "/dashboard/overview"
    },
    COUPON: {
        FETCH: "/coupons/all",
        CREATE: "/coupons/add",
        UPDATE: (id: string) => `/coupons/update/${id}`,
        DELETE: (id: string) => `/coupons/delete/${id}`,
        TOGGLE: (id: string) => `/coupons/${id}/toggle`,
        RESTORE: (id: string) => `/coupons/${id}/restore`,
        PERMANENT_DELETE: (id: string) => `/coupons/${id}/permanent-delete`,
    },
    PAYMENT: {
        REFUND: (id: string) => `/payment/${id}/refund`,
    },
    ANALYTICS: {
        SALES: "/analytics/sales",
        TOP_PRODUCTS: "/analytics/top-products",
        TOP_VENDORS: "/analytics/top-vendors",
        CATEGORY_SALES: "/analytics/category-sales",
        CUSTOMER_GROWTH: "/analytics/customer-growth",
        ORDER_STATUS: "/analytics/order-status",
        LOW_STOCK: "/analytics/low-stock",
    },
    NOTIFICATION: {
        FETCH: "/notifications/all",
        MY: "/notifications/my",
        UNREAD_COUNT: "/notifications/unread-count",
        CREATE: "/notifications/add",
        DELETE: (id: string) => `/notifications/${id}/delete`,
        READ: (id: string) => `/notifications/${id}/read`,
        READ_ALL: "/notifications/read-all",
        HIDE: (id: string) => `/notifications/${id}/hide`,
    },
    BANNER: {
        FETCH: "/banners/all",
        CREATE: "/banners/add",
        UPDATE: (id: string) => `/banners/${id}/update`,
        DELETE: (id: string) => `/banners/${id}/delete`,
        TOGGLE: (id: string) => `/banners/${id}/toggle-status`,
    },
    PAGE: {
        FETCH: "/pages/all",
        CREATE: "/pages/add",
        UPDATE: (id: string) => `/pages/${id}/update`,
        DELETE: (id: string) => `/pages/${id}/delete`,
        TOGGLE_PUBLISH: (id: string) => `/pages/${id}/toggle-publish`,
    },
    BLOG: {
        FETCH: "/blogs/admin/all",
        CREATE: "/blogs/add",
        UPDATE: (id: string) => `/blogs/update/${id}`,
        DELETE: (id: string) => `/blogs/delete/${id}`,
        PUBLISH: (id: string) => `/blogs/${id}/publish`,
        UNPUBLISH: (id: string) => `/blogs/${id}/unpublish`,
        FEATURED: (id: string) => `/blogs/${id}/featured`,
    },
    SETTING: {
        GET: "/settings/get",
        UPDATE: "/settings/update",
        MEDIA: "/settings/media",
    },
    GIFT_CARD: {
        FETCH: "/gift-cards/all",
        CREATE: "/gift-cards/add",
        TOGGLE: (id: string) => `/gift-cards/${id}/toggle`,
        DELETE: (id: string) => `/gift-cards/${id}/delete`,
        RESTORE: (id: string) => `/gift-cards/${id}/restore`,
        PERMANENT_DELETE: (id: string) => `/gift-cards/${id}/permanent-delete`,
    },
    TICKET: {
        FETCH: "/tickets/admin/all",
        DETAIL: (id: string) => `/tickets/${id}`,
        ASSIGN: (id: string) => `/tickets/${id}/assign`,
        STATUS: (id: string) => `/tickets/${id}/status`,
        PRIORITY: (id: string) => `/tickets/${id}/priority`,
        REPLY: (id: string) => `/tickets/${id}/reply`,
    },
    RETURN: {
        FETCH_ADMIN: "/returns/admin/all",
        DETAIL: (id: string) => `/returns/${id}`,
        APPROVE: (id: string) => `/returns/${id}/approve`,
        REJECT: (id: string) => `/returns/${id}/reject`,
        SCHEDULE_PICKUP: (id: string) => `/returns/${id}/schedule-pickup`,
        PICKED_UP: (id: string) => `/returns/${id}/picked-up`,
        RECEIVED: (id: string) => `/returns/${id}/received`,
        REFUND: (id: string) => `/returns/${id}/refund`,
    },
    REVIEW: {
        FETCH_ADMIN: "/reviews/admin/all",
        FETCH_REPORTED: "/reviews/admin/reported",
        TOGGLE_APPROVAL: (id: string) => `/reviews/${id}/toggle-approval`,
        RESOLVE_REPORT: (id: string) => `/reviews/${id}/resolve-report`,
        DELETE: (id: string) => `/reviews/${id}/admin-delete`,
    },
    REFUND: {
        FETCH_ADMIN: "/refunds/admin/all",
        DETAIL: (id: string) => `/refunds/${id}`,
        INITIATE: "/refunds/initiate",
        PROCESS: (id: string) => `/refunds/${id}/process`,
        RETRY: (id: string) => `/refunds/${id}/retry`,
        CANCEL: (id: string) => `/refunds/${id}/cancel`,
    },
    PAYOUT: {
        FETCH_ADMIN: "/payouts/admin/all",
        SUMMARY: "/payouts/admin/summary",
        PROCESS: (id: string) => `/payouts/${id}/process`,
        REJECT: (id: string) => `/payouts/${id}/reject`,
    },
    WAREHOUSE: {
        FETCH_ADMIN: "/warehouses/admin/all",
        TOGGLE: (id: string) => `/warehouses/${id}/toggle-status`,
    },
    INVENTORY: {
        FETCH_LOGS_ADMIN: "/inventory/admin/logs",
        LOW_STOCK: "/inventory/low-stock",
        SUMMARY: "/inventory/summary",
    },
}

export default ENDPOINTS