const QUERY_KEY = {
    USER: "user",
    CATEGORY: "category",
    BRAND: "brand",
    ORDER: "order",
    SHIPMENT: "shipment",
    DASHBOARD: "dashboard",
    PRODUCT: "product",
    ADMIN: "admin",
    COUPON: "coupon",
    VENDOR: "vendor",
    CUSTOMER: "customer",
    ANALYTICS: "analytics",
    NOTIFICATION: "notification",
    BANNER: "banner_cms",
    PAGE: "page_cms",
    BLOG: "blog_cms",
    SETTING: "setting",
    GIFT_CARD: "gift_card",
    TICKET: "ticket",
    RETURN: "return",
    REVIEW: "review",
    REFUND: "refund",
    PAYOUT: "payout",
    WAREHOUSE: "warehouse",
    INVENTORY: "inventory",
}

export default QUERY_KEY